### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [ZaynabGhazi/Parstagram#1]
Nice work, Zaynab. We put together a detailed Project 4 Feedback Guide here: (http://courses.codepath.org/snippets/android_university_fast_track/feedback_guides/project_4_feedback) which covers the most common issues with this project. Read through the feedback guide point-by-point to determine how you could improve your submission.

It looks like your video walkthrough doesn't seem to show one of the stretch features you listed wherein it allows the logged in user to add a profile photo

We hope you enjoyed the course and learned a lot in the process and look forward to see what you build for your final internship project!

**Comment by ZaynabGhazi** [comment]
Hi! Thank you for your feedback. I believe I changed the profile picture in the first video walkthrough in the README (user woman- end of gif)
